version: '3'
services:
  reversi:
    image: onlykeno/reversi:latest
    container_name: reversi_new
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=server.kedi-server.de
      - VALIDATION=http
      - EMAIL=kenodirks@outlook.de
      - ONLY_SUBDOMAINS=false
    restart: unless-stopped
