name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Image
        run: |
          docker build -t registry.kedi-server.de/reversi:latest .

      - name: Push the Docker image
        run: |
          docker push registry.kedi-server.de/reversi:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portainer Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"key": "value"}' url-einfügen
